"""Helper automations for Motion Lights Test Rig."""

# Add this to your automations.yaml or create as YAML automations in UI

automations:
  - id: motion_test_rig_motion_on
    alias: "Motion Test Rig: Turn ON motion"
    description: "When toggle switch is ON, activate motion sensor"
    trigger:
      platform: state
      entity_id: input_boolean.motion_test_rig_toggle
      to: "on"
    action:
      service: homeassistant.turn_on
      data:
        entity_id: binary_sensor.{{ room_name }}_motion

  - id: motion_test_rig_motion_off
    alias: "Motion Test Rig: Turn OFF motion"
    description: "When toggle switch is OFF, deactivate motion sensor"
    trigger:
      platform: state
      entity_id: input_boolean.motion_test_rig_toggle
      to: "off"
    action:
      service: homeassistant.turn_off
      data:
        entity_id: binary_sensor.{{ room_name }}_motion
